[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests
pythonpath = .
addopts = -p no:pytest_homeassistant_custom_component
filterwarnings =
    ignore:Inheritance class HomeAssistantApplication from web.Application is discouraged:DeprecationWarning
